name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Clear npm proxy config
        run: |
          npm config delete proxy || true
          npm config delete http-proxy || true
          npm config delete https-proxy || true
      - name: Install
        run: npm ci
      - name: Lint (no bloqueante)
        run: npm run lint || true
      - name: Typecheck
        run: npm run type-check
      - name: Build
        run: npm run build
      - name: Verificación de arquitectura
        run: npm run verify:repo
